pub mod anchor_map;
pub mod background;
pub mod core_render;
mod core_render_diagram;
mod core_render_lifecycle;
pub(crate) mod diagram_cache;
pub mod extension_table;
mod render_workers;
pub mod renderer;
pub mod types;
pub mod ui;
pub mod viewer_state;
pub use types::ViewerState;

#[cfg(test)]
mod tests;

pub mod section;
mod section_show;
pub mod utils;
pub use section::*;
mod image_background;
mod image_background_region;
mod image_background_region_model;
pub mod image_fallback;
pub mod images;
pub use images::*;
pub mod fullscreen;
pub mod fullscreen_local;
pub mod fullscreen_svg;
mod image_raster;
pub mod slideshow;
pub use fullscreen::*;
pub mod html;
pub mod math;
pub use html::*;
pub use math::*;
pub use renderer::*;
pub use types::*;
pub(crate) mod section_images;
