version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/crates/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    groups:
      actions-dependencies:
        patterns:
          - "*"
