use std::path::PathBuf;

use crate::app_state::ExportFormat;
use crate::state::document::ViewMode;
use katana_platform::{PaneOrder, SplitDirection};

#[derive(Debug, PartialEq, Clone)]
pub enum AppAction {
    InstallUpdate,
    PickOpenWorkspace,
    OpenWorkspace(PathBuf),
    SelectDocument(PathBuf),
    SelectDocumentAndJump {
        path: PathBuf,
        line: usize,
        byte_range: std::ops::Range<usize>,
    },
    OpenMultipleDocuments(Vec<PathBuf>),
    RemoveWorkspace(String),
    RemoveWorkspaceHistory(String),
    ShowStatusMessage(String, crate::app_state::StatusType),
    CloseWorkspace,
    CloseDocument(usize),
    CloseActiveDocument,
    ForceCloseDocument(usize),
    UpdateBuffer(String),
    ReplaceText {
        span: std::ops::Range<usize>,
        replacement: String,
    },
    ToggleTaskList {
        global_index: usize,
        new_state: char,
    },
    SaveDocument,
    RefreshDiagrams,
    RefreshDocument {
        is_manual: bool,
    },
    ChangeLanguage(String),
    ToggleSettings,
    ToggleExportPanel,
    ToggleStoryPanel,
    ToggleToolsPanel,
    ToggleAbout,
    ToggleToc,
    ToggleWorkspacePanel,
    ToggleExplorer,
    ToggleHistoryPanel,
    ToggleSearchModal,
    ToggleCommandPalette,
    ToggleKatanaCommandPalette,
    ToggleRailPopup(crate::state::layout::RailPopup),
    ToggleSlideshow,
    ToggleSlideshowHoverHighlight,
    ToggleSlideshowShowDiagramControls,
    ToggleExplorerFilter,
    CheckForUpdates,
    SetSplitDirection(SplitDirection),
    ToggleSplitMode,
    ToggleCodePreview,
    SetPaneOrder(PaneOrder),
    SetViewMode(ViewMode),
    ToggleScrollSync(bool),
    RefreshExplorer,
    ReorderActivityRail {
        from: usize,
        to: usize,
    },
    CreateFsNode {
        parent_dir: PathBuf,
        is_dir: bool,
        target_path: PathBuf,
    },
    RenameFsNode {
        target_path: PathBuf,
        new_path: PathBuf,
    },
    DeleteFsNode {
        target_path: PathBuf,
    },
    CloseOtherDocuments(usize),
    CloseAllDocuments,
    CloseDocumentsToRight(usize),
    CloseDocumentsToLeft(usize),
    TogglePinDocument(usize),
    RestoreClosedDocument,
    ReorderDocument {
        from: usize,
        to: usize,
        new_group_id: Option<Option<String>>,
    },
    ExportDocument(ExportFormat),
    AcceptTerms(String),
    DeclineTerms,
    ShowMetaInfo(PathBuf),
    RequestNewFile(PathBuf),
    RequestNewDirectory(PathBuf),
    RequestRename(PathBuf),
    RequestDelete(PathBuf),
    CopyPathToClipboard(PathBuf),
    CopyRelativePathToClipboard(PathBuf),
    RevealInOs(PathBuf),
    SkipVersion(String),
    DismissUpdate,
    ConfirmRelaunch,
    ShowReleaseNotes,
    OpenHelpDemo,
    OpenWelcomeScreen,
    OpenUserGuide,
    OpenGitHub,
    OpenOfficialWebsite,
    SwitchDemoLanguage(String),
    ClearAllCaches,
    CreateTabGroup {
        name: String,
        color_hex: String,
        initial_member: PathBuf,
    },
    CreateTabGroupMany {
        name: String,
        color_hex: String,
        members: Vec<PathBuf>,
    },
    AddTabToGroup {
        group_id: String,
        member: PathBuf,
    },
    AddTabsToGroup {
        group_id: String,
        members: Vec<PathBuf>,
    },
    RemoveTabFromGroup(PathBuf),
    RenameTabGroup {
        group_id: String,
        new_name: String,
    },
    ClearInlineRename,
    RecolorTabGroup {
        group_id: String,
        new_color: String,
    },
    CloseTabGroup(String),
    UngroupTabGroup(String),
    ToggleCollapseTabGroup(String),
    OpenDocSearch,
    ToggleDocSearch,
    DocSearchQueryChanged,
    DocSearchNext,
    DocSearchPrev,
    ToggleProblemsPanel,
    RefreshDiagnostics,
    /* WHY: Markdown authoring — insert/transform Markdown syntax around cursor or selection. */
    AuthorMarkdown(MarkdownAuthoringOp),
    /* WHY: Image ingest — attach a local file image or paste clipboard image into the document. */
    IngestImageFile,
    IngestClipboardImage,
    /* WHY: Reveal local image asset in OS file manager. */
    RevealImageAsset(std::path::PathBuf),
    Quit,
    None,
}

/// Operations available via the Markdown authoring command set.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum MarkdownAuthoringOp {
    /* WHY: Inline decorations */
    Bold,
    Italic,
    Strikethrough,
    InlineCode,
    /* WHY: Block / structural */
    Heading1,
    Heading2,
    Heading3,
    BulletList,
    NumberedList,
    Blockquote,
    CodeBlock,
    HorizontalRule,
    /* WHY: Reference structures */
    InsertLink,
    InsertTable,
}
