use std::path::PathBuf;

use crate::app_state::ExportFormat;
use crate::state::document::ViewMode;
use katana_platform::{PaneOrder, SplitDirection};

#[derive(Debug, PartialEq, Clone)]
pub enum AppAction {
    InstallUpdate,
    PickOpenWorkspace,
    OpenWorkspace(PathBuf),
    SelectDocument(PathBuf),
    SelectDocumentAndJump {
        path: PathBuf,
        line: usize,
        byte_range: std::ops::Range<usize>,
    },
    OpenMultipleDocuments(Vec<PathBuf>),
    RemoveWorkspace(String),
    RemoveWorkspaceHistory(String),
    ShowStatusMessage(String, crate::app_state::StatusType),
    CloseWorkspace,
    CloseDocument(usize),
    ForceCloseDocument(usize),
    UpdateBuffer(String),
    ReplaceText {
        span: std::ops::Range<usize>,
        replacement: String,
    },
    ToggleTaskList {
        global_index: usize,
        new_state: char,
    },
    SaveDocument,
    RefreshDiagrams,
    RefreshDocument {
        is_manual: bool,
    },
    ChangeLanguage(String),
    ToggleSettings,
    ToggleAbout,
    ToggleToc,
    ToggleWorkspacePanel,
    ToggleExplorer,
    ToggleHistoryPanel,
    ToggleSearchModal,
    ToggleCommandPalette,
    ToggleSlideshow,
    ToggleExplorerFilter,
    CheckForUpdates,
    SetSplitDirection(SplitDirection),
    SetPaneOrder(PaneOrder),
    SetViewMode(ViewMode),
    ToggleScrollSync(bool),
    RefreshExplorer,
    ReorderActivityRail {
        from: usize,
        to: usize,
    },
    CreateFsNode {
        parent_dir: PathBuf,
        is_dir: bool,
        target_path: PathBuf,
    },
    RenameFsNode {
        target_path: PathBuf,
        new_path: PathBuf,
    },
    DeleteFsNode {
        target_path: PathBuf,
    },
    CloseOtherDocuments(usize),
    CloseAllDocuments,
    CloseDocumentsToRight(usize),
    CloseDocumentsToLeft(usize),
    TogglePinDocument(usize),
    RestoreClosedDocument,
    ReorderDocument {
        from: usize,
        to: usize,
        new_group_id: Option<Option<String>>,
    },
    ExportDocument(ExportFormat),
    AcceptTerms(String),
    DeclineTerms,
    ShowMetaInfo(PathBuf),
    RequestNewFile(PathBuf),
    RequestNewDirectory(PathBuf),
    RequestRename(PathBuf),
    RequestDelete(PathBuf),
    CopyPathToClipboard(PathBuf),
    CopyRelativePathToClipboard(PathBuf),
    RevealInOs(PathBuf),
    SkipVersion(String),
    DismissUpdate,
    ConfirmRelaunch,
    ShowReleaseNotes,
    ClearAllCaches,
    CreateTabGroup {
        name: String,
        color_hex: String,
        initial_member: PathBuf,
    },
    AddTabToGroup {
        group_id: String,
        member: PathBuf,
    },
    RemoveTabFromGroup(PathBuf),
    RenameTabGroup {
        group_id: String,
        new_name: String,
    },
    ClearInlineRename,
    RecolorTabGroup {
        group_id: String,
        new_color: String,
    },
    CloseTabGroup(String),
    UngroupTabGroup(String),
    ToggleCollapseTabGroup(String),
    OpenDocSearch,
    DocSearchQueryChanged,
    DocSearchNext,
    DocSearchPrev,
    ToggleProblemsPanel,
    RefreshDiagnostics,
    None,
}
